-- Create "log" table
CREATE TABLE public."log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" TEXT NOT NULL DEFAULT '',
  "name" TEXT NOT NULL DEFAULT '',
  "status" BOOLEAN NOT NULL DEFAULT FALSE,
  "data" TEXT NOT NULL DEFAULT ''
);

-- Create "config" table
CREATE TABLE public."config" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL DEFAULT '',
  "timeZone" TEXT NOT NULL DEFAULT '',
  "path_api" TEXT NOT NULL DEFAULT '',
  "path_gui" TEXT NOT NULL DEFAULT '',
  "webapi_title" TEXT NOT NULL DEFAULT '',
  "webapi_description" TEXT NOT NULL DEFAULT '',
  "webapi_version" TEXT NOT NULL DEFAULT '',
  "webapi_openapi_url" TEXT NOT NULL DEFAULT '',
  "webapi_docs_url" TEXT NOT NULL DEFAULT '',
  "webapi_redoc_url" TEXT NOT NULL DEFAULT '',
  "webapi_key" TEXT NOT NULL DEFAULT '',
  "webapi_host" TEXT NOT NULL DEFAULT '',
  "webapi_port" INTEGER DEFAULT 0,
  "webapi_workers" INTEGER DEFAULT 0,
  "nginx_api_host" TEXT NOT NULL DEFAULT '',
  "nginx_api_port" INTEGER DEFAULT 0,
  "nginx_api_key" TEXT NOT NULL DEFAULT '',
  "nginx_gui_host" TEXT NOT NULL DEFAULT '',
  "nginx_gui_port" INTEGER DEFAULT 0,
  "nginx_gui_key" TEXT NOT NULL DEFAULT '',
  "git_email" TEXT NOT NULL DEFAULT '',
  "git_name" TEXT NOT NULL DEFAULT '',
  "git_key" TEXT NOT NULL DEFAULT '',
  "hotspod_ssid" TEXT NOT NULL DEFAULT '',
  "hotspod_ip" TEXT NOT NULL DEFAULT '',
  "hotspod_pass" TEXT NOT NULL DEFAULT '',
  "wifi_ssid" TEXT NOT NULL DEFAULT '',
  "wifi_ip" TEXT NOT NULL DEFAULT '',
  "wifi_pass" TEXT NOT NULL DEFAULT '',
  "debug" BOOLEAN NOT NULL DEFAULT FALSE,
  "log" BOOLEAN NOT NULL DEFAULT FALSE,
  "verbose" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "user" table
CREATE TABLE public."user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL DEFAULT '',
  "username" TEXT NOT NULL DEFAULT '',
  "password" TEXT NOT NULL DEFAULT '',
  "key" TEXT NOT NULL DEFAULT '',
  "email" TEXT NOT NULL DEFAULT '',
  "phone" TEXT NOT NULL DEFAULT '',
  "tg_id" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "timer" table
CREATE TABLE public."timer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER NOT NULL DEFAULT 0,
  "name" TEXT NOT NULL DEFAULT '',
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "timer_item" table
CREATE TABLE public."timer_item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timer_id" INTEGER NOT NULL DEFAULT 0,
  "name" TEXT NOT NULL DEFAULT '',
  "value_from" TEXT NOT NULL DEFAULT '',
  "value_to" TEXT NOT NULL DEFAULT '',
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "timer_device" table
CREATE TABLE public."timer_device" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timer_id" INTEGER NOT NULL DEFAULT 0,
  "device_id" INTEGER NOT NULL DEFAULT 0,
  "command_id" INTEGER NOT NULL DEFAULT 0,
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "timer_limit" table
CREATE TABLE public."timer_limit" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" INTEGER NOT NULL DEFAULT 0,
  "command_from_id" INTEGER NOT NULL DEFAULT 0,
  "command_to_id" INTEGER NOT NULL DEFAULT 0,
  "value" INTEGER NOT NULL DEFAULT 0,
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "device" table
CREATE TABLE public."device" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zone_id" INTEGER NOT NULL DEFAULT 0,
  "port_id" INTEGER NOT NULL DEFAULT 0,
  "power_id" INTEGER NOT NULL DEFAULT 0,
  "command_id" INTEGER NOT NULL DEFAULT 0,
  "value" INTEGER NOT NULL DEFAULT 0,
  "tune" INTEGER NOT NULL DEFAULT 0,
  "date" TEXT NOT NULL DEFAULT '',
  "address" TEXT NOT NULL DEFAULT '',
  "name" TEXT NOT NULL DEFAULT '',
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "port" table
CREATE TABLE public."port" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER NOT NULL DEFAULT 0,
  "name" TEXT NOT NULL DEFAULT '',
  "pin" INTEGER DEFAULT 0,
  "port" INTEGER DEFAULT 0,
  "value" INTEGER DEFAULT 0,
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE,
  "protocol" TEXT NOT NULL DEFAULT '',
  "type" TEXT NOT NULL DEFAULT ''
);

-- Create "device_command" table
CREATE TABLE public."device_command" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" INTEGER NOT NULL DEFAULT 0,
  "name" TEXT NOT NULL DEFAULT '',
  "value_from" INTEGER DEFAULT 0,
  "value_to" INTEGER DEFAULT 0,
  "delay" INTEGER DEFAULT 0,
  "description" TEXT NOT NULL DEFAULT '',
  "reload" BOOLEAN NOT NULL DEFAULT FALSE,
  "enable" BOOLEAN NOT NULL DEFAULT FALSE,
  "type" TEXT NOT NULL DEFAULT ''
);

-- Create "zone" table
CREATE TABLE public."zone" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER NOT NULL DEFAULT 0,
  "name" TEXT NOT NULL DEFAULT '',
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "zone_command" table
CREATE TABLE public."zone_command" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zone_id" INTEGER NOT NULL DEFAULT 0,
  "name" TEXT NOT NULL DEFAULT '',
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "zone_command_if" table
CREATE TABLE public."zone_command_if" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL DEFAULT '',
  "zone_command_id" INTEGER NOT NULL DEFAULT 0,
  "device_id" INTEGER NOT NULL DEFAULT 0,
  "command_id" INTEGER NOT NULL DEFAULT 0,
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create "zone_command_action" table
CREATE TABLE public."zone_command_action" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL DEFAULT '',
  "zone_command_id" INTEGER NOT NULL DEFAULT 0,
  "device_id" INTEGER NOT NULL DEFAULT 0,
  "command_id" INTEGER DEFAULT 0,
  "description" TEXT NOT NULL DEFAULT '',
  "enable" BOOLEAN NOT NULL DEFAULT FALSE
);
